services:
  frenchlegacy-bridge:
    container_name: frenchlegacy-bridge
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config/settings.json:/app/config/settings.json:ro
      - bridge_data:/app/data
    environment:
      - TZ=Europe/Paris
    networks:
      - fl-network
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    labels:
      - "user.frenchlegacy=allowed"


volumes:
  bridge_data:
    name: fl_bridge_prod
    driver: local